### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kiranneupane** [Bonitasoft-Community/page_changepassword#1]
Hi There,

I am getting following error while trying to implement this. Can you please advise. 

1 error
] with root cause
javax.servlet.ServletException: startup failed:
C:\BonitaBPMCommunity-7.3.3\workspace\tomcat\temp\bonita_portal_11316@npdc-bpm\tenants\1\pages\custompage_changepassword\Index.groovy: 9: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 9, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;

**Comment by pierre-yves-monnet** [comment]
The version 1 used a subscription class (start by com).
In the V2, only community class is used.
